### ISSUE TITLE
Not working with AKS when RBAC is enabled

### ISSUE THREAD

**Issue by cwoolum** [Microsoft/ApplicationInsights-Kubernetes#124]
Gettin the following error message in my logs

```
Query Failed. Request Message: Method: GET, RequestUri: 'https://10.0.0.1/api/v1/namespaces/dev2/pods', Version: 2.0, Content: &lt;null&gt;, Headers:
 {
   Authorization: Bearer <Removed>
   Request-Context: appId=cid-v1:3f57fa57-3411-4143-8776-af6e9ca94b9b
   x-ms-request-root-id: ff93c843-4ef530fc59b11c6b
   x-ms-request-id: |ff93c843-4ef530fc59b11c6b.
   Request-Id: |ff93c843-4ef530fc59b11c6b.
 }. Status Code: Forbidden. Phase: Forbidden
```

**Comment by karolz-ms** [comment]
@cwoolum this is kind of expected

You will have to run your deployments under a ServiceAccount that is in a ClusterRole that has access to "get", "list" and "watch" verbs on pods and namespaces resources. Check K8s docs on ServiceAccount, ClusterRole and ClusterRoleBinding

**Comment by cwoolum** [comment]
I tried the following template but I'm still getting the same error
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pitch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pitch-metrics-reader
rules:
- apiGroups: [""]
  resources: ["endpoints", "namespaces"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pitch-metrics-reader
subjects:
- kind: ServiceAccount
  name: pitch
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pitch-metrics-reader

```

Did I miss something?
