### ISSUE TITLE
Need to provide namespaces support

### ISSUE THREAD

**Issue by yoavrubin** [Microsoft/ApplicationInsights-Kubernetes#125]
My app uses a setup where namespaces are used, and keeps the default namespace empty. 
It seems that this kind of setup causes [this](https://github.com/Microsoft/ApplicationInsights-Kubernetes/blob/e8ca46c753ab3e8291032b0a2bc3d4e58105ff36/src/ApplicationInsights.Kubernetes/K8sEnvironmentFactory.cs#L85) call to return an empty node list that later on fails [this](https://github.com/Microsoft/ApplicationInsights-Kubernetes/blob/e8ca46c753ab3e8291032b0a2bc3d4e58105ff36/src/ApplicationInsights.Kubernetes/K8sEnvironmentFactory.cs#L89) call and thus prevents the ApplicationInsights-Kubernetes from working. 
Is it possible to provide a support for specifying what's the namespace to use? 
@xiaomi7732

**Comment by xiaomi7732** [comment]
Troubleshoot with @yoavrubin and find the last issue before it works, in the binding, the sa account will be in the proper namespace:
```yaml
# actual binding to the role
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: metrics-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: propernamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-reader
```

I'll close this issue due to no further actions.
