### ISSUE TITLE
403 still persists after applying the RBAC configuration

### ISSUE THREAD

**Issue by razvangoga** [microsoft/ApplicationInsights-Kubernetes#216]
Hi,

I'm trying to deploy a .Net core 3.1 Worker Service application int AKS.
After running the RBAC configuration 1 of the 4 K8s API requests still return a 403 (before applying the RBAC all 4 would fail with 403).

My setup is 

- AKS with Kubernetes v1.16.10
- .Net Core 3.1.301 Worker Service using the following Docker build file and using the Microsoft.ApplicationInsights.Kubernetes v1.1.2 nuget package. The InitializationTimeout is set to **_TimeSpan.FromSeconds(15)_**

Docker file
```
FROM mcr.microsoft.com/dotnet/core/runtime:3.1.5-alpine3.12 AS base
FROM` mcr.microsoft.com/dotnet/core/sdk:3.1.301-alpine3.12 AS build
```

![image](https://user-images.githubusercontent.com/1067494/90157945-a7e33000-dd8e-11ea-8dba-706b4a4b0f15.png)

What need further configuration?

**Comment by xiaomi7732** [comment]
Hi razvangoga, the configuration steps seems correct. When you do deploy the ClusterRoleBinding, does it have the same namespace as in the replica?

**Comment by razvangoga** [comment]
Yes, as far as I can tell - but the K8 deployment namespace is not set in the K8 deployment yaml, but rather in the Azure Devops release pipeline (i forgot to mention that the services are deployed via Azure Devops, if this makes any difference)

In AKS the pods run in my namespace (and they run so far without any issue)

Below are the redacted K8 deployment yaml and Azure Devops step.

``` yaml
steps:
- task: Kubernetes@1
  displayName: 'kubectl apply'
  inputs:
    kubernetesServiceEndpoint: 'my-azure-aks'
    namespace: name-of-namespace
    command: apply
    useConfigurationFile: true
    configuration: '$(System.DefaultWorkingDirectory)/my-worker-service/deployment/deploy.yaml'
```

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-worker-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: my-worker-service
  template:
    metadata:
      labels:
        app: my-worker-service
    spec:
      containers:
      - name: my-worker-service
        image: myacr.azurecr.io/my-worker-service:#{Build.BuildId}#
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Staging"
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: "some-instrumentaion key"
```

**Comment by bbridges** [comment]
Had a similar issue to this with 403 for replicasets, adding the `apps` api group to the ClusterRole allowed this request to work. The ClusterRole in the RBAC example still uses the older `extensions` api group.

**Comment by razvangoga** [comment]
Thanks for the tip @bbridges! That did the trick

![image](https://user-images.githubusercontent.com/1067494/90621327-e015c300-e213-11ea-8c51-c51be9a41cd7.png)

The updated RBAC config i used is:

``` yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: appinsights-k8s-property-reader
rules:
- apiGroups: ["","extensions", "apps"]
  resources: ["pods","nodes", "replicasets","deployments"]
  verbs: ["get", "watch", "list"]
---
# actual binding to the role
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: appinsights-k8s-property-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: name-of-namespace
roleRef:
  kind: ClusterRole
  name: appinsights-k8s-property-reader
  apiGroup: rbac.authorization.k8s.io
```

@xiaomi7732 - what are your thoughts on this?
