### ISSUE TITLE
RBAC SARole suggestion

### ISSUE THREAD

**Issue by Olli64** [microsoft/ApplicationInsights-Kubernetes#219]
Greetings,

I stumbled across problem with multiple namespaces (dev, test, prod) with each having their own application insights.

As I'm not that familiar with kubernetes and dont have too much in-depth knowledge of the Roles/RoleBindings.

I had a small challenge here on how to make application insights able to collect information from all of the namespaces to enrich request telemetry.
(appins = application insights)
So I have 3 appins resources, ai-dev, ai-test and ai-prod.
I have multiple backend services with each having dev, test and prod environments (and linked to corresponding appins instance)
I have 3 namespaces in kubernetes (dev, test, prod)

Problem was that I could only get information from "prod" namespace by default and then I found this [github guide](https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/develop/examples/BasicUsage_clr21_RBAC)

I added that clusterrolebinding to all namespaces just to notice that ofcourse it is overwriting it everytime because I was using same name (didnt understand that I could rename the ClusterRoleBinding to whatever)

Then finally I decided to create RoleBinding that referenced that ClusterRole to each namespace and finally after that I got it working.

Then at last I tried to rename those ClusterRoleBindings to different names in different namespaces and got it working also.

But what I couldn't figure out, why this is created as ClusterRoleBinding rather than RoleBinding?

As you must reference an service account from a namespace, that binds that ClusterRoleBinding to a namespace anyways (which loses the meaning of ClusterRoleBinding?)

So should it rather be RoleBinding which is scoped to a specific namespace as is the serviceaccount we should be giving the permissions to?

As in:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appinsights-k8s-property-reader
rules:
- apiGroups: ["","extensions", "apps"]
  resources: ["pods","nodes", "replicasets","deployments"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: appinsights-test-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: <test-namespace>
roleRef:
  kind: ClusterRole
  name: appinsights-k8s-property-reader
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: appinsights-prod-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: <prod-namespace>
roleRef:
  kind: ClusterRole
  name: appinsights-k8s-property-reader
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: appinsights-dev-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: <dev-namespace>
roleRef:
  kind: ClusterRole
  name: appinsights-k8s-property-reader
  apiGroup: rbac.authorization.k8s.io
```

Sincerely,
Olli Elolähde

**Comment by xiaomi7732** [comment]
@Olli64 thanks for bringing this up. I think it make sense to use **RoleBinding** than **ClusterRoleBinding** and you have a perfect example of how will it look like in real scenario.

Do you want to submit a PR so that you will take the credit, or if you prefer, I can prepare a PR. Which one do you prefer?

**Comment by xiaomi7732** [comment]
Here's an example from the K8s official documentation:

> A RoleBinding can also reference a ClusterRole to grant the permissions defined in that ClusterRole to resources inside the RoleBinding's namespace. This kind of reference lets you define a set of common roles across your cluster, then reuse them within multiple namespaces.

> For instance, even though the following RoleBinding refers to a ClusterRole, "dave" (the subject, case sensitive) will only be able to read Secrets in the "development" namespace, because the RoleBinding's namespace (in its metadata) is "development".

```yaml
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "dave" to read secrets in the "development" namespace.
# You need to already have a ClusterRole named "secret-reader".
kind: RoleBinding
metadata:
  name: read-secrets
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "development" namespace.
  namespace: development
subjects:
- kind: User
  name: dave # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
```
